<footer
    class="pdf-footer"
>

    <table
        class="footer-table"
    >
        <tr>

            <!-- INSTRUCTOR -->

            <td
                class="footer-cell"
            >

                <span
                    class="signature-name"
                >
                    {{
                        $branding[
                            'instructor_name'
                        ]
                    }}
                </span>


                <div
                    class="signature-role"
                >
                    University Instructor
                    ({{ $branding['component'] }})
                </div>

            </td>


            <!-- UNIVERSITY ADMIN -->

            <td
                class="footer-cell"
            >

                <span
                    class="signature-name"
                >
                    {{
                        $branding[
                            'administrator_name'
                        ]
                    }}
                </span>


                <div
                    class="signature-role"
                >
                    University Administrator
                </div>

            </td>

        </tr>
    </table>


    <div
        class="generated"
    >
        Generated by NSTPHUB ·
        {{
            $branding[
                'generated_at'
            ]
        }}
    </div>

</footer>